### ISSUE TITLE
Region Sub-Region

### ISSUE THREAD

**Issue by arthurwelle** [kylemcdonald/covid-mobility-data#1]
Nice Work! I was almost ready doing the same thing in R, than I found out about your work. I aspire to get at your level some day. 
A few things: first the most important, your final tsv result has only one region level. Could you add two columns "Country" and "Region". That will help someone looking for subnational divisions of a specific country.
Second, and far less important: as far as I could tell all the graphs are -80% +80%, but the data is not bound to this constrains, and if that occurs google shows -100% (without changing the scale) and up to 127% (without changing the scale) in witch point there is a cut off. Note that positive values can deviate from median until infinite, but decrease from median the maximum of -100%. I guess this is less important for most of the data fit your paramethers.
Regards! And thanks again for your amazing work.

**Comment by kylemcdonald** [comment]
thanks for your feedback and encouragement! i am in the process of rewriting this to use the postscript data, which will be more accurate & should capture the out-of-range data, even if it isn't visible. i will also think of some way to update the country/region distinction. it's a little strange right now because the data includes both a PDF for the US (with stats for each state) but also PDFs for each state (with stats for each county).
